#!/bin/bash
#
# This profile maps the bash library scripts to aliases and performs other setup.
# techphoria.net

function ostype () {
    case "$(uname -s)" in
       Darwin)
            if [ "$1" == "darwin" ]; then
                return 0
            fi
            ;;
       Linux)
            if [ "$1" == "linux" ]; then
                return 0
            fi
            ;;
       CYGWIN*)
            if [ "$1" == "cygwin" ]; then
                return 0
            fi
            ;;
    esac
    return 1
}

export __scriptdir=`dirname "${BASH_SOURCE[0]}"`
chmod +x $__scriptdir/sbin/*.sh

if ostype darwin; then
    chmod +x $__scriptdir/mac/*.sh
    export __scriptpath=`$__scriptdir/mac/readlink.sh "${BASH_SOURCE[0]}"`
    source $__scriptdir/mac/setjdk.sh

else
    export __scriptpath=`readlink -n "${BASH_SOURCE[0]}"`
fi


alias rnx="$__scriptdir/sbin/regex-renamer.sh"

function config {
	vim $__scriptpath
}

function apply {
	source $__scriptpath
}
